#include "stm32f10x.h"

int main()
{
	//ENABLE CLOCKS FOR WHATEVER THINGS YOU ARE USING I.E., UART AND INPUT/OUTPUT FOR THIS CASE
	RCC->APB2ENR |= RCC_APB2ENR_USART1EN | RCC_APB2ENR_IOPAEN ;
	// CONFIGURE MODER AND CNF FOR OUTPUT SPEED AND WHETHER O/P OR I/P 
	// HERE RX IS I/P AND BY DEFAULT ALL PINS ARE INPUT
	// WE HAVE TO SET TX AS OUTPUT WITH A PARTICULAR SPEED.
	GPIOA-> CRH |= GPIO_CRH_MODE9 | GPIO_CRH_CNF9_1 ;
	GPIOA -> CRH &= ~(GPIO_CRH_CNF9_0);
	//CNF9  1 0 >>>>ALTERNATE FUNC. O/P PUSH PULL
	//MODE9 1 1 >>>>50MHZ SLEW RATE
	
	//NOW SET BAUD RATE
	USART1-> BRR= 0x1D4C ;
  // NOW ENABLE TX,RX AND UART
	USART1->CR1 |= USART_CR1_RE | USART_CR1_TE | USART_CR1_UE ;
	
	while(1)
	{
		if(USART1->SR & USART_SR_RXNE)
		{
			char temp = USART1->DR ; // STORE IN TEMP WHATEVER IS RECEIVED
			USART1->DR = 0;
			USART1->DR = temp; // GIVE BACK WHATEVER RECEIVED
			while(!(USART1->SR & USART_SR_TC));//WAIT TILL TRANSMISSON COMPLETE
		}
		
	}
	
}